spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/upload?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: hanjinhao
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        hbm2ddl:
          auto: update

oss.bucketName: zhiwindrain
oss.accessKey: LTAI5tAy8bxW3LqpdWWxENNM
oss.secretKey: Qm7DHBosM6DUKj3tWztPJE3DF5YD73
oss.region: oss-cn-shanghai.aliyuncs.com

cos.bucketName: zhjwindrain-1305740870
cos.accessKey: AKIDOI4hBM8KZlDWhjefbP2pjUBjATccIsnY
cos.secretKey: oU2RikfQ3Xs483fBWjniU8cryvkPuOAm
cos.region: ap-nanjing

server:
  port: 8080